// Command makeStatic reads a set of files and writes a Go source file to "static.go"
// that declares a map of string constants containing contents of the input files.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"path/filepath"
	"unicode/utf8"
)

func main() {
	pk := os.Args[1]
	srcDir := os.Args[2]
	targetDir := os.Args[3]

	if err := makeStatic(pk, srcDir, targetDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func makeStatic(pk, srcDir, targetDir string) error {
	staticFile := filepath.Join(targetDir, "static.go")
	f, err := os.Create(staticFile)
	if err != nil {
		return err
	}
	defer f.Close()
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "%v\n\n%v\n\npackage %s\n\n", license, warning, pk)
	fmt.Fprintf(buf, "var StaticFiles = map[string]string{\n")

	srcDir = filepath.Clean(srcDir)
	if err := loopAddFiles(buf, srcDir, srcDir); err != nil {
		return err
	}

	fmt.Fprintln(buf, "}")
	fmtBuf, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	return ioutil.WriteFile(staticFile, fmtBuf, 0666)
}

// readDirNames reads the directory named by dirname and returns
// a sorted list of directory entries.
func readDirNames(dirname string) ([]string, error) {
	f, err := os.Open(dirname)
	if err != nil {
		return nil, err
	}
	names, err := f.Readdirnames(-1)
	f.Close()
	if err != nil {
		return nil, err
	}
	return names, nil
}

func loopAddFiles(buf *bytes.Buffer, rootDir string, readDir string) error {
	prefix := ""
	if len(readDir) > len(rootDir) {
		prefix = readDir[len(rootDir)+1:] + "/"
	}

	dirs, err := readDirNames(readDir)
	if err != nil {
		return err
	}

	for _, dir := range dirs {
		path := filepath.Join(readDir, dir)
		info, err := os.Lstat(path)
		if err != nil {
			return err
		}

		if info.IsDir() {
			if err := loopAddFiles(buf, rootDir, path); err != nil {
				return err
			}

			continue
		}

		fmt.Printf("add file %s\n", path)

		b, err := ioutil.ReadFile(path)
		if err != nil {
			return err
		}
		fmt.Fprintf(buf, "\n\t%q: ", prefix+info.Name())
		if utf8.Valid(b) {
			fmt.Fprintf(buf, "`%s`", sanitize(b))
		} else {
			fmt.Fprintf(buf, "%q", b)
		}

		fmt.Fprintln(buf, ",")
	}
	return nil
}

// sanitize prepares a valid UTF-8 string as a raw string constant.
func sanitize(b []byte) []byte {
	// Replace ` with `+"`"+`
	b = bytes.Replace(b, []byte("`"), []byte("`+\"`\"+`"), -1)

	// Replace BOM with `+"\xEF\xBB\xBF"+`
	// (A BOM is valid UTF-8 but not permitted in Go source files.
	// I wouldn't bother handling this, but for some insane reason
	// jquery.js has a BOM somewhere in the middle.)
	return bytes.Replace(b, []byte("\xEF\xBB\xBF"), []byte("`+\"\\xEF\\xBB\\xBF\"+`"), -1)
}

const warning = `// Code generated by "makestatic.go"; DO NOT EDIT.`

var license = `// Copyright 2019 wongoo. All rights reserved.`
